"""add_message_id_to_emails

Revision ID: 12ae29ed336a
Revises: ead2053ab31b
Create Date: 2025-03-06 02:21:42.681093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ae29ed336a'
down_revision = 'ead2053ab31b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.drop_constraint('contact_emails_contact_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contacts', ['contact_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contact_methods', schema=None) as batch_op:
        batch_op.alter_column('method_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.create_index('idx_contact_methods_value', ['value'], unique=False)
        batch_op.create_unique_constraint(None, ['value'])

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('position',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_emails_message_id'), ['message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_message_id'))
        batch_op.drop_column('message_id')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.alter_column('position',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('contact_methods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_contact_methods_value')
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('method_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('contact_emails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contact_emails_contact_id_fkey', 'contacts', ['contact_id'], ['id'])

    # ### end Alembic commands ###
